<?php

namespace common\models;

use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "clients".
 *
 * @property int $id
 * @property string $title
 * @property string $img
 */
class Clients extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'clients';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['title'], 'string', 'max' => 100],
            [['img'], 'string', 'max' => 200],
            [['file'], 'image']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'img' => 'Img',
            'file' => 'Image',
        ];
    }

    public function beforeSave($insert)
    {

        if ($file = UploadedFile::getInstance($this, 'file')) {

            if (!file_exists($this->getFolder())) {
                FileHelper::createDirectory($this->getFolder());
            }
            if (!empty($this->img) && $this->img != null && file_exists($this->getFolder() . $this->img)) {
                unlink($this->getFolder() . $this->img);
            }
            $this->img = strtotime('now') . '_' . \Yii::$app->getSecurity()->generateRandomString(6) . '.' . $file->extension;
            $file->saveAs($this->getFolder() . $this->img);

        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function deleteImage()
    {
        if (file_exists($this->getFolder() . $this->img)) {
            unlink($this->getFolder() . $this->img);
        }
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getFolder()
    {
        return Yii::getAlias('@image') . '/clients/';
    }

}
